#pragma once

#define BTN_PLAYER_UP 		VK_UP		   //
#define BTN_PLAYER_DOWN		VK_DOWN		   //
#define BTN_PLAYER_LEFT		VK_LEFT		   //
#define BTN_PLAYER_RIGHT	VK_RIGHT	   //

#define CAMERA_SPEED		48

#define MAP_WIDTH			WINSIZEX
#define MAP_HEIGHT			WINSIZEY


#define FACE_MAX			300
#define NORMAL_IMAGE_MAX	1
#define COMBAT_IMAGE_MAX	26
#define WEAPON_IMAGE_MAX	1
#define ARMOR_IMAGE_MAX		1
#define SUBITEM_IMAGE_MAX	1

#define UNIT_ATTACK_RANGE_MAX	7

typedef enum DIRECTION
{
	DIRECTION_DN,
	DIRECTION_UP,
	DIRECTION_LF,
	DIRECTION_RG,
};

enum ATTACK_RANGE
{
	ATTACK_RANGE_MELEE4,	//1칸씩 4방향
	ATTACK_RANGE_MELEE8,	//1칸씩 8방향
	ATTACK_RANGE_ARROW2,	//2칸
};

enum TEAM
{
	TEAM_NONE = -1,

	TEAM_PLAYER,
	TEAM_FRIEND,
	TEAM_ENEMY,

	TEAM_MAX
};


enum UNIT_BATTLE_IMAGE
{
	UNIT_BATTLE_IMAGE_JOJO,		//조조
	UNIT_BATTLE_IMAGE_HAHU,		//하후돈
	UNIT_BATTLE_IMAGE_YUPO,		//여포
	UNIT_BATTLE_IMAGE1,			//보병
	UNIT_BATTLE_IMAGE2,			//기병
	UNIT_BATTLE_IMAGE3,			//궁병
	UNIT_BATTLE_IMAGE4,			//궁기병
	UNIT_BATTLE_IMAGE5,			//도사
	UNIT_BATTLE_IMAGE6,			//법사
	UNIT_BATTLE_IMAGE7,			//무도가
	UNIT_BATTLE_IMAGE8,			//석기

	UNIT_BATTLE_IMAGE_MAX,
};

enum FONTVERSION
{
	FONTVERSION_SAMJOJO,
	FONTVERSION_STORY,
	FONTVERSION_SAMJOJO_AJINJI,
	FONTVERSION_SAMJOJO_ASEJONG,
	FONTVERSION_SAMJOJO_HEE,

	FONTVERSION_MAX
};

enum BRUSHVERSION
{
	BRUSHVERSION_WHITE,
	BRUSHVERSION_GRAY,
	BRUSHVERSION_MARGENTA,
	BRUSHVERSION_TILE,


	BRUSHVERSION_MAX
};